### ISSUE TITLE
Track circles with opencv

### ISSUE THREAD

**Issue by isZumpo** [felixnorden/moppepojkar#45]
I found out that you can make opencv a lot quicker by doing the camera work on a seperate thread:https://www.pyimagesearch.com/2015/12/28/increasing-raspberry-pi-fps-with-python-and-opencv/

Also there is a tutorial for tracking a moving ball that works very well for what we're trying to do too: https://www.pyimagesearch.com/2015/09/21/opencv-track-object-movement/

**Comment by konglobemeralt** [comment]
Closing as this is done
